name: build + publish the site
# building the thing, then commiting it to the gh-pages branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: build the site
    runs-on: ubuntu-latest

    steps:
      - name: checking out
        uses: actions/checkout@v2

      - name: use node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: building the thing
        run: |
          npm ci
          npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: 'gh-pages'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
